name: refresh-triggerdev-workflow

on:
  deployment_status:

jobs:
  my-job:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    name: send-webhook
    runs-on: ubuntu-latest
    steps:
      - run: curl -XPOST $TRIGGERDEV_WEBHOOK_URL
        env:
          TRIGGERDEV_WEBHOOK_URL: ${{ secrets.TRIGGERDEV_WEBHOOK_URL }}
