name: testing-workflow

on:
  push:

jobs:
  my-job:
    name: testing-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: |
          cp .env.example .env
          bun run build
