name: testing-workflow

on:
  push:

jobs:
  my-job:
    name: testing-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install
      - run: |
          cp .env.example .env
          pnpm run check
          pnpm run build
          pnpm run lint
