name: testing-workflow

on:
  push:

jobs:
  my-job:
    name: testing-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
